version: 2.1
parameters:
    artefact-version-prefix:
     default: "0.0.3-alpha"
     type: string

jobs:
   build:
     docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0-preview
     steps:
      - checkout
      - run: 
          name: Restore
          command: Invoke-Expression "dotnet restore"
      - run: 
          name: Build
          command: Invoke-Expression "dotnet build -p:PackageVersion=<<pipeline.parameters.artefact-version-prefix>>.$env:CIRCLE_BUILD_NUM --no-restore"
      - run:
          name: "Run Tests"
          command: dotnet test -v n --results-directory:test-results --test-adapter-path:. --no-build
      - store_test_results:
          path: test-results
          when: always      
      - run:
          name: "Dotnet pack"
          command: Invoke-Expression "dotnet pack --configuration Release -p:PackageVersion=<<pipeline.parameters.artefact-version-prefix>>.$env:CIRCLE_BUILD_NUM --no-restore"
      - run:
           name: "Copy artifacts"
           command: Copy-Item Microsoft.Build.BinlogRedactor.*.*nupkg .\nugets
      - store_artifacts:
           path: .\nugets

workflows:
      version: 2
      build-deploy:
         jobs:
            - build
