version: 2.1
parameters:
    artefact-version-prefix:
     default: "0.0.3-alpha"
     type: string

jobs:
   build:
     docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0-preview
     steps:
      - run:
          name: install ssh and git
          command: apk add --update openssh-client git
      - checkout
      - run: 
          name: List checkouts
          command: ls -R
      - run: 
          name: Restore
          command: dotnet restore
      - run: 
          name: Build
          command: dotnet build -p:PackageVersion=<<pipeline.parameters.artefact-version-prefix>>-$CIRCLE_BUILD_NUM --no-restore
      - run:
          name: "Run Tests"
          command: dotnet test -v n --results-directory:test-results --test-adapter-path:. --no-build
      - store_test_results:
          path: test-results
          when: always      
      - run:
          name: "Dotnet pack"
          command: dotnet pack --configuration Release -p:PackageVersion=<<pipeline.parameters.artefact-version-prefix>>-$CIRCLE_BUILD_NUM --no-restore
      - run:
           name: "List artifacts"
           command: find ./ -type f -name 'MSBuild.BinlogRedactor.*.*nupkg'
      - run:
           name: "Copy artifacts"
           command: |
              shopt -s globstar
              mkdir nugets
              cp **/MSBuild.BinlogRedactor.*.*nupkg ./nugets
      - store_artifacts:
           path: ./nugets

workflows:
      version: 2
      build-deploy:
         jobs:
            - build
